mxm_wifiex: fix build errors on L6.16 kernel next tree
When build wifi driver based on L6.16 kernel next tree, will observe the
following build errors. These are caused by the upstream patches:
41cb08555c41 ("treewide, timers: Rename from_timer() to timer_container_of()")
b74947b4f6ff ("wifi: cfg80211/mac80211: Add support to get radio index")
Need to change corresponding API here to avoid the build break.

Build error logs:
mlinux/moal_main.h:498:54: note: each undeclared identifier is reported only once for each function it appears in
In file included from mlinux/moal_cfg80211.h:26,
                 from mlinux/moal_sta_cfg80211.c:23:
mlinux/moal_main.h: In function ‘woal_timer_handler’:
mlinux/moal_main.h:498:33: error: implicit declaration of function ‘from_timer’; did you mean ‘mod_timer’? [-Werror=implicit-function-declaration]
  498 |         pmoal_drv_timer timer = from_timer(timer, t, tl);
      |                                 ^~~~~~~~~~
      |                                 mod_timer
mlinux/moal_sta_cfg80211.c: At top level:
mlinux/moal_sta_cfg80211.c:403:29: error: initialization of ‘int (*)(struct wiphy *, int,  u32)’ {aka ‘int (*)(struct wiphy *, int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct wiphy *, u32)’ {aka ‘int (*)(struct wiphy *, unsigned int)’} [-Werror=incompatible-pointer-types]
  403 |         .set_wiphy_params = woal_cfg80211_set_wiphy_params,
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:403:29: note: (near initialization for ‘woal_cfg80211_ops.set_wiphy_params’)
mlinux/moal_sta_cfg80211.c:428:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, int,  enum nl80211_tx_power_setting,  int)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, enum nl80211_tx_power_setting,  int)’ [-Werror=incompatible-pointer-types]
  428 |         .set_tx_power = woal_cfg80211_set_tx_power,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:428:25: note: (near initialization for ‘woal_cfg80211_ops.set_tx_power’)
mlinux/moal_sta_cfg80211.c:429:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, int,  unsigned int,  int *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, unsigned int,  int *)’ [-Werror=incompatible-pointer-types]
  429 |         .get_tx_power = woal_cfg80211_get_tx_power,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:429:25: note: (near initialization for ‘woal_cfg80211_ops.get_tx_power’)
mlinux/moal_sta_cfg80211.c:444:24: error: initialization of ‘int (*)(struct wiphy *, int,  u32,  u32)’ {aka ‘int (*)(struct wiphy *, int,  unsigned int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct wiphy *, u32,  u32)’ {aka ‘int (*)(struct wiphy *, unsigned int,  unsigned int)’} [-Werror=incompatible-pointer-types]
  444 |         .set_antenna = woal_cfg80211_set_antenna,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:444:24: note: (near initialization for ‘woal_cfg80211_ops.set_antenna’)
mlinux/moal_sta_cfg80211.c:445:24: error: initialization of ‘int (*)(struct wiphy *, int,  u32 *, u32 *)’ {aka ‘int (*)(struct wiphy *, int,  unsigned int *, unsigned int *)’} from incompatible pointer type ‘int (*)(struct wiphy *, u32 *, u32 *)’ {aka ‘int (*)(struct wiphy *, unsigned int *, unsigned int *)’} [-Werror=incompatible-pointer-types]
  445 |         .get_antenna = woal_cfg80211_get_antenna,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:445:24: note: (near initialization for ‘woal_cfg80211_ops.get_antenna’)

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>