mxm_wifiex: fix build warnings on L6.13 kernel next tree
When build wifi driver based on L6.13 kernel next tree, will observe the
following build errors. This is caused by the following three upstream
patches. Need to change corresponding API here to avoid the build break.

02f220b52670 ("wifi: ipw2x00/lib80211: move remaining lib80211 into
libipw")
7a53af85d3bb ("wifi: cfg80211: send MLO links tx power info in
GET_INTERFACE")
9c4f83092775 ("wifi: cfg80211: pass net_device to .set_monitor_channel")

In file included from mlinux/moal_main.c:29:
mlinux/moal_main.h:136:10: fatal error: net/lib80211.h: No such file or directory
  136 | #include <net/lib80211.h>
      |          ^~~~~~~~~~~~~~~~
 compilation terminated.
make[3]: *** [/kernel-source/scripts/Makefile.build:194: mlinux/moal_main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from mlinux/moal_eth_ioctl.c:29:
mlinux/moal_main.h:136:10: fatal error: net/lib80211.h: No such file or directory
  136 | #include <net/lib80211.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

mlinux/moal_sta_cfg80211.c:379:25: error: initialization of ‘int (*)(struct wiphy *, struct wireless_dev *, unsigned int,  int *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct wireless_dev *, int *)’ [-Werror=incompatible-pointer-types]
  379 |         .get_tx_power = woal_cfg80211_get_tx_power,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:379:25: note: (near initialization for ‘woal_cfg80211_ops.get_tx_power’)
mlinux/moal_sta_cfg80211.c:468:32: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct cfg80211_chan_def *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct cfg80211_chan_def *)’ [-Werror=incompatible-pointer-types]
  468 |         .set_monitor_channel = woal_cfg80211_set_monitor_channel,
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mlinux/moal_sta_cfg80211.c:468:32: note: (near initialization for ‘woal_cfg80211_ops.set_monitor_channel’)
cc1: some warnings being treated as errors
make[4]: *** [/kernel-source/scripts/Makefile.build:194: mlinux/moal_sta_cfg80211.o] Error 1

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>