mxm_wifiex: fix build error on L6.19 kernel next tree
When build wifi driver based on L6.19 kernel next tree, will observe the
following build error. It is caused by the upstream patch:
2b5e9f9b7e414 ("net: Convert struct sockaddr to fixed-size "sa_data[14]"")
Need to change corresponding API here to avoid the build break.

Build error logs:
mlinux/moal_eth_ioctl.c: In function ‘woal_priv_get_ap’:
mlinux/moal_eth_ioctl.c:6970:55: error: ‘struct sockaddr’ has no member named ‘sa_data_min’; did you mean ‘sa_data’?
 6970 |                                 sizeof(mwr->u.ap_addr.sa_data_min));
      |                                                       ^~~~~~~~~~~
      |                                                       sa_data
make[4]: *** [/scripts/Makefile.build:287: mlinux/moal_eth_ioctl.o] Error 1

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>