mxm_wifiex: fix build errors on L7.0 kernel next tree
When build wifi driver based on L7.0 kernel next tree, will observe the
following build errors. These are caused by the upstream patches:
7c6084d7fa4e6 ("wifi: cfg80211: support key installation on non-netdev wdevs")
033fe322f5852 ("wifi: nl80211/cfg80211: support stations of non-netdev interfaces")
08e6183ed2568 ("wifi: move action code from per-type frame structs")
Need to change corresponding APIs here to avoid the build break.

mlinux/moal_shim.c: In function ‘moal_recv_event’:
mlinux/moal_shim.c:5041:62: error: passing argument 1 of ‘cfg80211_new_sta’ from incompatible pointer type [-Wincompatible-pointer-types]
 5041 |                                         cfg80211_new_sta(priv->netdev,
      |                                                          ~~~~^~~~~~~~
      |                                                              |
      |                                                              struct net_device *
In file included from mlinux/moal_main.h:160,
                 from mlinux/moal_shim.c:28:
linux-nxp-rebase/include/net/cfg80211.h:8972:44: note: expected ‘struct wireless_dev *’ but argument is of type ‘struct net_device *’
 8972 | void cfg80211_new_sta(struct wireless_dev *wdev, const u8 *mac_addr,
      |                       ~~~~~~~~~~~~~~~~~~~~~^~~~
mlinux/moal_sta_cfg80211.c: In function ‘woal_construct_tdls_action_frame’:
mlinux/moal_sta_cfg80211.c:9329:55: error: ‘struct <anonymous>’ has no member named ‘u’
 9329 |                 skb_put(skb, 1 + sizeof(mgmt->u.action.u.tdls_discover_resp));
      |                                                       ^
mlinux/moal_sta_cfg80211.c:9331:31: error: ‘struct <anonymous>’ has no member named ‘u’
 9331 |                 mgmt->u.action.u.tdls_discover_resp.action_code =
      |                               ^
mlinux/moal_sta_cfg80211.c:9333:31: error: ‘struct <anonymous>’ has no member named ‘u’
 9333 |                 mgmt->u.action.u.tdls_discover_resp.dialog_token = dialog_token;
      |                               ^
mlinux/moal_sta_cfg80211.c:9334:31: error: ‘struct <anonymous>’ has no member named ‘u’
 9334 |                 mgmt->u.action.u.tdls_discover_resp.capability =
      |                               ^
mlinux/moal_sta_cfg80211.c:9338:50: error: ‘struct <anonymous>’ has no member named ‘u’
 9338 |                         1 + sizeof(mgmt->u.action.u.tdls_discover_resp));
      |                                                  ^
mlinux/moal_sta_cfg80211.c: In function ‘woal_cfg80211_uap_add_station’:
mlinux/moal_sta_cfg80211.c:11172:42: error: passing argument 1 of ‘cfg80211_new_sta’ from incompatible pointer type [-Wincompatible-pointer-types]
11172 |                         cfg80211_new_sta(dev, mac, sinfo, GFP_KERNEL);
      |                                          ^~~
      |                                          |
      |                                          struct net_device *
In file included from mlinux/moal_main.h:160,
                 from mlinux/moal_cfg80211.h:26:
linux-nxp-rebase/include/net/cfg80211.h:8972:44: note: expected ‘struct wireless_dev *’ but argument is of type ‘struct net_device *’
 8972 | void cfg80211_new_sta(struct wireless_dev *wdev, const u8 *mac_addr,
      |                       ~~~~~~~~~~~~~~~~~~~~~^~~~

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>