mxm_wifiex: fix build error on L6.14 kernel next tree
When build wifi driver based on L6.14 kernel next tree, will observe the
following build error. This is caused by the upstream patch:
f835bdae7167 ("net: remove init_dummy_netdev()").
Need to change corresponding API here to avoid the build break.

Build error logs:
mlinux/moal_main.c: In function 'woal_add_card':
mlinux/moal_main.c:13469:17: error: implicit declaration of function 'init_dummy_netdev' [-Wimplicit-function-declaration]
13469 | init_dummy_netdev(&handle->napi_dev);

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>